name:                turing
version:             0.1.0.0
github:              "Ant0wan/Ft_turing"
license:             BSD3
author:              "Antoine Barthelemy"
maintainer:          "antoine@linux.com"
copyright:           "BSD"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A 42 project implementating a Turing machine
category:            "42"

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Ant0wan/Ft_turing#readme>

dependencies:
- base >= 4.7 && < 5
- cmdargs
- aeson

library:
  source-dirs: src

executables:
  turing:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -dynamic
    - -Werror
    - -Wextra
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -fno-warn-orphans
    dependencies:
    - turing

tests:
  turing-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - turing
